"""Add TypeTask (Enum)

Revision ID: cbb9f5f3e300
Revises: cff49413b9e5
Create Date: 2024-10-03 18:14:11.055406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum

# revision identifiers, used by Alembic.
revision: str = 'cbb9f5f3e300'
down_revision: Union[str, None] = 'cff49413b9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Определение ENUM типа
typetask_enum = Enum('Developer', 'Manager', 'Tester', name='typetask')


def upgrade() -> None:
    # Создание ENUM типа
    typetask_enum.create(op.get_bind())

    # Добавление столбца с ENUM типом
    op.add_column('tasks', sa.Column('type_task', typetask_enum, nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'type_task')
    # ### end Alembic commands ###
