services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: sh -c "alembic upgrade head && uvicorn application.main:main_app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backend

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A application.background_tasks.send_message:celery worker --loglevel=INFO
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backend

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flower
    command: celery -A application.background_tasks.send_message:celery flower --port=5555
    depends_on:
      - redis
      - celery
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: